# model
#model_name_or_path: E:\PyCharm\PreTrainModel\qwen_7b_chat
model_name_or_path: /mnt/e/PyCharm/PreTrainModel/qwen_7b_chat
# method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

# dataset
dataset: new_train_datas4
dataset_dir: ../data
template: qwen
cutoff_len: 1024
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 4

# output
output_dir: saves/qwen_7b_chat_sft
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 0.00001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

# eval
val_size: 0.1
per_device_eval_batch_size: 4
evaluation_strategy: steps
eval_steps: 200
